### ISSUE TITLE
simulate field data

### ISSUE THREAD

**Issue by aekendig** [aekendig/CodingEnvSci_UF_FieldTrip#4]
Simulate field data to write data analysis and visualization activity. Data include (per plot):
1. Species richness
2. Max height or median height from 3 measurements (different canopy levels)
3. Number of pollinators
4. Number of leaves with damage

**Comment by whalend** [comment]
Hey, wondering where you were at on this and whether I could help track down or generate these example data?

**Comment by aekendig** [comment]
I haven't started on this yet, so yes, any help you can give would be great! If you have data collected from Bivens that doesn't need that much cleaning, that could work. Otherwise, just simulating with random value generators will serve our purposes. These are the types of data students will collect in the field.

**Comment by aekendig** [comment]
I added the equivalent for the greenhouse experiment (invasive_species_enemies.Rmd) in case that helps clarify what I mean by this issue.

**Comment by whalend** [comment]
Yep, I've got some general plot-level measurements of vegetation height and biomass data that is easy to pull together. I think I can get species richness from data Cathy recorded too.
